listen: :4433

tls:
  cert: /root/cert/hy.doubebly.eu.org.cer
  key: /root/cert/hy.doubebly.eu.org.key

auth:
  type: password
  password: chika

masquerade:
  type: proxy
  proxy:
    url: https://www.lovelive-anime.jp
    rewriteHost: true
